Import libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

Import dataset

In [3]:
data=pd.read_table(r'D:\P004.txt')

In [4]:
data.head()

   CurrentMilk  Previous  Fat  Protein  Days  Lactation  I79
0           45        45  5.5      8.9    21          5    0
1           86        86  4.4      4.1    25          4    0
2           50        50  6.5      4.0    25          7    0
3           42        42  7.4      4.1    25          2    0
4           61        61  3.8      3.8    33          2    0

Split the dataset in predictor variable and response variable

In [5]:
X=data.iloc[:,:-1]

In [6]:
X.head()

   CurrentMilk  Previous  Fat  Protein  Days  Lactation
0           45        45  5.5      8.9    21          5
1           86        86  4.4      4.1    25          4
2           50        50  6.5      4.0    25          7
3           42        42  7.4      4.1    25          2
4           61        61  3.8      3.8    33          2